name: Lint
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js v24
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install --verbose
      - run: npx patch-package
      - run: npm run test
